### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by sockmaster27**
Not exhaustive, but enough to run the website without having to use Node v16

### CODE REVIEW

**Comment by sockmaster27** [comment]
There's some deprecation warning that I can't get to go away for the life of me

**Comment by magnus-madsen** [comment]
Its a bit massive, 20k lines changes for one dependency? :/

**Comment by sockmaster27** [comment]
It should be one major version bump and alot of minor version upgrades

**Comment by magnus-madsen** [comment]
Can this be closed?

**Pull request closed without merging**
