### PR TITLE
feat: Add new examples

### PR DESCRIPTION
**Pull request by ninaandrup**
Related to #63

### CODE REVIEW

**Comment by ninaandrup** [comment]
I'm not sure why old changes from `Home.js` etc are showing up in this PR, when they are already in master ...

**Comment by magnus-madsen** [comment]
Try to rebase onto master. It should be painless and solve the problem. (Then do a force push).

Possibly take a manual backup of Samples.js before proceeding.

**Comment by ninaandrup** [comment]
It should be fixed now, but I'm very unsure of the order of the examples.

**Comment by ninaandrup** [comment]
@magnus-madsen I'm very unsure of the order, but other than that it should be ready

**Comment by magnus-madsen** [comment]
Looks good. Do you want to update the main signatures later or in this PR?

**Comment by ninaandrup** [comment]
> Looks good. Do you want to update the main signatures later or in this PR?

I can do it in this PR :-)

**Comment by ninaandrup** [comment]
> Looks good. Do you want to update the main signatures later or in this PR?

Done

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
