### PR TITLE
feat: add 'VS Code' page

### LINKED ISSUE #103: Add page with Visual Studio Code Gifs
Add page that demonstrates each VSCode feature.

### PR DESCRIPTION
**Pull request by sockmaster27**
Fixes #103

### CODE REVIEW

**Comment by sockmaster27** [comment]
It look kind of empty. I'll have to confess that I'm not great at copy writing.

image

**Comment by magnus-madsen** [comment]
- [ ] Lets try the `webp` format and see how the file sizes are.
- [ ] Let's fix a specific resolution (so all videos are the same size and fonts appear the same size).
- [ ] In the examples, lets try to avoid showing "hanging" `{` or other code that is not relevant. For example, the `ToString` derivation shows a lot of code, but most of it is not relevant.
- [ ] Dont worry about copy-editing, if you just write some initial text, I can help improve it.

Let focus on getting these three videos ready and then we can work on the next.

**Comment by magnus-madsen** [comment]
- [ ] Experiment with light theme?

**Comment by magnus-madsen** [comment]
https://www.screentogif.com/

**Comment by sockmaster27** [comment]
Webp is locked to a very low framerate so it's hard to compare, but the one I did was about 60KB vs the mp4's (60fps) 100~200KB, so I wouldn't say it's an important difference.

**Comment by magnus-madsen** [comment]
Here is a 30FPS webp file: https://flix.dev/test01.webp which requires only 27KB.

This is 10x less than the mp4 file, so I am definitely convinced we should go with that. 

Just drop OBS and use ScreenToGif with ffmpeg.

**Comment by sockmaster27** [comment]
> Here is a 30FPS webp file: https://flix.dev/test01.webp which requires only 27KB

I thought the cap was lower, and to be fair that one is also less than a quarter of the resolution of the others, but I agree.

**Comment by sockmaster27** [comment]
Here's how it looks now:
image

**Comment by sockmaster27** [comment]
It's pretty busy-looking with everything moving at once.
Maybe they should only play on hover?

**Comment by sockmaster27** [comment]
image

**Comment by magnus-madsen** [comment]
What do you think about using a light theme?

**Comment by magnus-madsen** [comment]
> It's pretty busy-looking with everything moving at once. Maybe they should only play on hover?

People might not know to hover, but I understand the issue.

**Comment by sockmaster27** [comment]
> What do you think about using a light theme?

I can definitely try it out, but I'd think the dark is more recognizable as VS Code.

**Comment by sockmaster27** [comment]
> > It's pretty busy-looking with everything moving at once. Maybe they should only play on hover?
> 
> People might not know to hover, but I understand the issue.

Perhaps show an overlayed play button?

**Comment by magnus-madsen** [comment]
> Perhaps show an overlayed play button?

Lets keep the outplay for now

**Comment by magnus-madsen** [comment]
> What do you think about using a light theme?

Instead, what if we make this page black instead of white (by black I mean the same background as VSCode).

**Comment by magnus-madsen** [comment]
The text would have to be white.

**Comment by sockmaster27** [comment]
Could work, I'll try it

**Comment by magnus-madsen** [comment]
I think some more vertical space would also be useful.

**Comment by sockmaster27** [comment]
With added spacing:

image

**Comment by magnus-madsen** [comment]
Hmm. I still think it looks jarring. But if you insist, surely we can have some black box around that part of the page?

**Comment by magnus-madsen** [comment]
Like, just put everything below the horizontal ruler in black box.

**Comment by magnus-madsen** [comment]
What's the status on this?

**Comment by sockmaster27** [comment]
> What's the status on this?

Annoying 😞 procrastinating

**Comment by sockmaster27** [comment]
I think I'll try light mode though

**Comment by magnus-madsen** [comment]
Fixed in master.

**Pull request closed without merging**
